export default [
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"},
    {name: "Adrian Rodriguez", university:"Columbia University in the City of New York", snapchat: "arod_hypebeast", instagram: "iloveadrian", profile: "https://media-exp1.licdn.com/dms/image/C4D03AQHoi-mm4-ACRg/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=1gHCI1yim7uOg7KM68lO8kR_qM-GDyprRtysatWTSW0"}
];